### ISSUE TITLE
Mockups de la primera version de la tienda

### ISSUE THREAD

**Issue by serudda** [serudda/reward-system#158]
### Descripción de la tarea

Es necesario definir la primera versión de la tienda. Su estructura, base, colores, logo, etc.

-----

### Criterios de aceptación

- [ ] Dejar adjunto una imagen o archivo donde se pueda ver los mockups de la tienda.

**Comment by JCruz-Dev** [comment]
@serudda yo podria trabajar en esta tarea, cual serian los requerimientos o hay algun Wireframe para empezar a tomar ideas?

No se si aún este listo los colores de la marca de Indie Creators y será aplicado a esta tienda o tendrá un concepto diferente?

**Comment by serudda** [comment]
Wua me encanta @bkerz aquí les dejo mis investigaciones:

Creo que debería ser dark mode, estos estilos son minimal y a la vez muy elegantes... combinado con la opción que propones, creo que podríamos hacer algo bien lindo.



![Image](https://user-images.githubusercontent.com/10075532/227791781-ebf57866-c64b-4a55-b849-6f2fa65f3854.png)



![Image](https://user-images.githubusercontent.com/10075532/227791807-24a5d980-5346-45e1-a18e-a1ccedc8c6c5.png)


Voy a agregar una propuesta mezclando todas las opciones propuestas

**Comment by serudda** [comment]
Doy por cerrado este Issue, ya tenemos las cosas un poco mas claras con las ideas que se han venido compartiendo. Asi que siento que esta tarea la podemos dar por completada.
