### ISSUE TITLE
[Bug]: Dangerous URL 💀

### ISSUE THREAD

**Issue by Lucas-FullStackX** [serudda/reward-system#215]
### Discord Username

Lucas Leguizamo

### Severity Level

High

### Description of the Bug

the site is detected as dangerous and does not allow access.
![image](https://user-images.githubusercontent.com/78978776/232252435-6fc37a59-fc6e-49e3-a690-a405fdf6866a.png)

### Operating System

Windows

### Browser(s)

Chrome

### Browser Version(s)

Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serudda** [comment]
DONE
