### ISSUE TITLE
[Bug]: Messages are displayed in the chat, they should be private.

### ISSUE THREAD

**Issue by jardave21** [serudda/reward-system#216]
### Severity Level

High

### Description of the Bug

A bug happened!
![isuue](https://user-images.githubusercontent.com/91550154/232333311-a3463705-64bc-4ea1-9c99-3cce83c8f25c.JPG)
The "pay" and "give coins" commands display messages and part of the code in the chat.

### Operating System

Windows

### Browser(s)

Chrome

### Browser Version(s)

Latest

### Relevant Log Output

```zsh
The Banker
BOT
 — Today at 11:31 AM
[
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "nan",
    "path": [
      "coins"
    ],
    "message": "Expected number, received nan"
  }
]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by serudda** [comment]
DONE:
https://github.com/serudda/reward-system/pull/217
