### ISSUE TITLE
Averiguar si Github API nos devuelve los custom fields

### ISSUE THREAD

**Issue by serudda** [serudda/reward-system#47]
### Descripción de la tarea

Ya que GitHub implemento la posibilidad de agregar "custom fields" en cada issue. Es necesario hacer un refactor en el flujo que tenemos actualmente dentro del repo [reward-system](https://github.com/Indie-Creator-Community/reward-system) para poder obtener la cantidad de indieToken del campo "**Reward**":

![Image](https://user-images.githubusercontent.com/10075532/221441411-0b983b32-cf23-403f-a024-4dfd9d3b1e03.png)

Averiguar si la API de Github nos permite obtener estos custom fields.

-----

### Criterios de aceptación

- [ ] Hacer pruebas de concepto, y compartir hallazgos en los comentarios de este issue.
- [ ] Compartir el flujo en detalle, con screeenshots, e información relevante.
- [ ] Mencionar a @sruda en los comentarios avisando que la tarea se da por resuelta.

**Comment by Xch4rt** [comment]
Hola @serudda , he hecho pruebas rápidas y me he topado con lo siguiente

Qué utilicé?
1. Github CLI
2. Powershell

Comandos:

1. `gh auth login`: Aquí pedirá elegir entre loguearse con HTTP o SSH (en mi caso elegí HTTP por los memes realmente, tenia 2 llaves guardadas y no sabía cual era cual XD)
![imagen](https://user-images.githubusercontent.com/35347784/224528442-fdf93002-2152-4fee-8321-1908f21a44b3.png)

2. Luego de configurar el inicio de sesión, ejecuta el siguiente comando 
` gh api repos/:github_username/:repo_name/issues/:issue_id -H 'Accept: application/vnd.github.v3+json' -f fields='body,custom_fields(":custom_field_name")'`. Ejemplifico:

![imagen](https://user-images.githubusercontent.com/35347784/224528539-7f63d2e5-cf0f-4cef-9196-283e5831b1f6.png)

El problema con el que me encuentro es que me arroja un 403, diciendo que debo de tener permisos de administrador en el repo. Tal vez si sigues esta secuencia te funcione, adjunto imagen:

![imagen](https://user-images.githubusercontent.com/35347784/224528571-d1432592-44f7-40cb-8087-a839eb6e313e.png)

**Comment by serudda** [comment]
Este issue se resolvio en otro PR. Closed
