### ISSUE TITLE
Maquetar Store Page

### ISSUE THREAD

**Issue by serudda** [serudda/reward-system#73]
### Descripción de la tarea

Diseñar y maquetar la página de la tienda del reward System (StorePage). Buscar referentes, ideas, benchmark.

-----

### Criterios de aceptación

- [ ] Dejar en Figma o en Excalidraw una primera version de la página Store v0.1.0

**Comment by jardave21** [comment]
La tienda puede tener 2 secciones, una para poder contratar servicios y otra para comprar productos  y un filtro que me permita saber por usuario lo que está ofreciendo,

**Comment by serudda** [comment]
@jardave21 a que te refieres con "contratar servicios"
