### ISSUE TITLE
Disenar Wireframe en Figma de la Store Page

### ISSUE THREAD

**Issue by serudda** [serudda/reward-system#77]
### Descripción de la tarea

Hacer una lluvia de ideas, con el fin de poder diseñar los mockups de baja, media o alta fidelidad, de la nueva página: Store.
Proponer diferentes opciones de ser posible.

-----

### Criterios de aceptación

- [ ] Dejar en un archivo de Figma las propuestas diseñadas.

**Comment by Tech-Code1** [comment]
Empece a hacer la investigación de algunos diseños interesantes que encontre, me ayude de algunos resultados de Midjurney y otros que encontre por google, aca escogi como los mejorcitos:

![Pantallazo 16-03-2023 22 38 16](https://user-images.githubusercontent.com/61479618/225806838-9abf821b-450b-4d23-9b56-ac0f64810478.png)


Empece el wireframe de aterrizaje, para que de entrada no sea de una la tienda, para dar un poco de contexto a las personas nuevas que la ven. Me imagine una moneda(El Indie token) flotando un poco mas un poco de informa acompañando, acá dejo el bosquejo:

![Pantallazo 16-03-2023 22 37 15](https://user-images.githubusercontent.com/61479618/225807096-5781c15b-5d98-4697-8606-4864fe69e7d6.png)


También dejo el link del Figma en donde ando trabajandolo: https://www.figma.com/file/ockLD1jO7YX9nARlCy2gvP/Untitled?node-id=0%3A1&t=ZHDQlR252roe94xs-1

Mañana espero poder hacer algún wireframe de la tienda en si.

**Comment by serudda** [comment]
@Tech-Code1 tú estuviste en el último Stream?, ahi dimos unas indicaciones, y tomamos como ejemplo productos como Airbnb, para tener una línea más minimalista, recuerda q esto es un Side Project y tenemos que movernos rápido... así qué diseños muy elaborados y 3D por ahora los vamos a evitar

**Comment by Tech-Code1** [comment]
Me la vi pero muy a pedazos, la repetire, y en base a eso hare los diseños entonces ;)

**Comment by Tech-Code1** [comment]
Seru, me vi otra vez el video, decidi mejor trabajarlo por componentes por acá hice este

![Pantallazo 17-03-2023 20 25 07](https://user-images.githubusercontent.com/61479618/226075845-788e2c55-78a8-4afd-89e6-59adde4e3967.png)

Este seria una opción para las cards de la tienda

**Comment by bkerz** [comment]
@serudda @Tech-Code1 ¿Qué tal si dejan algún enlace de figma para que cualquiera pueda aportar más ideas ahí dentro y luego se revisa cual sería la mejor?

**Comment by Tech-Code1** [comment]
@bkerz Si mira el link de Figma por acá: 
https://www.figma.com/file/ockLD1jO7YX9nARlCy2gvP/Untitled?node-id=0%3A1&t=dreB1ZJLzJgWum6y-1

Si necesitas que te de permisos me envias un mensaje al privado por Discrod:
[*Tech_Code*]#0001

**Comment by hardstonepaul** [comment]
Hola todos hice una tienda en prestashop es una idea para poder solucionar varios issues que genera crear una tienda: pedidos, clientes, productos, atención al cliente, transporte, idiomas, monedas, etc.
[Indie Creator Tienda](https://catalogoespacial.com/indie/)
[Documentación Prestashop](https://devdocs.prestashop-project.org/)
Pensaría yo que nos podemos conectar por medio de la API que genera la tienda. pienso que nos ahorraría mucho tiempo de desarrollo.
Primero mirar si es viable usarla **???** y luego hacer un modulo para conectar los usuarios con sus indie tokens  para que los puedan usar en la tienda.

**Comment by hardstonepaul** [comment]
Ustedes en el backend tienen mas criterio que yo, si no es viable mejor no.

**Comment by serudda** [comment]
Por ahora voy a tomar las ideas que han compartido por aqui... y con base a eso trabajare... es una primera version asi que no deberiamos gastarle mucho tiempo.

**Comment by serudda** [comment]
El alcance de esta tarea es dejar adjunto ideas de como deberia ser la tienda... aqui no definiremos tech stack... 

Por cuestiones de tiempo, creo que no voy a disenar todas las vistas en FIgma... con las ideas que han ido surgiendo en la tareas https://github.com/serudda/reward-system/issues/158 creo que con eso vamos a empezar a maquetar.
